import assert from "node:assert/strict";
import { describe, it } from "node:test";
import {
  CoreError,
  canonicalPayload,
  createCoreClient,
  isTerminal,
  signRequest,
  signedHeaders,
} from "../src/core-client.ts";

/**
 * Generated by upstream's own signer, not by this implementation:
 *
 *   node -e "import('./src/auth/source-auth-sign.ts').then(m => …)"   (in ai-base)
 *
 * That is the point of the vector. A duplicated wire format that is only checked
 * against itself proves the code is self-consistent and says nothing about
 * whether the core will accept it — and a drifted signature fails as a bare 401
 * that names neither half.
 */
const VECTOR = {
  secret: "topsecret-shared-key-for-vector-0123",
  timestamp: 1_700_000_000,
  method: "POST",
  path: "/v1/turns?async=1",
  body: '{"a":1}',
  canonical: 'POST\n/v1/turns?async=1\n{"a":1}',
  signature: "v0=b4426c0be69af5aa36cce022eca44cb4313cd643e23488cea763c952a56cbacf",
};

describe("the wire format, pinned to upstream", () => {
  it("builds the canonical string upstream builds", () => {
    assert.equal(canonicalPayload(VECTOR.method, VECTOR.path, VECTOR.body), VECTOR.canonical);
  });

  it("produces the exact signature upstream produces", () => {
    assert.equal(signRequest(VECTOR.secret, VECTOR.timestamp, VECTOR.canonical), VECTOR.signature);
  });

  it("emits both headers upstream reads", () => {
    const h = signedHeaders(VECTOR.secret, VECTOR.method, VECTOR.path, VECTOR.body, VECTOR.timestamp);
    assert.deepEqual(h, { "x-timestamp": "1700000000", "x-signature": VECTOR.signature });
  });

  it("signs nothing when there is no secret, rather than sending an unverifiable signature", () => {
    // A core started with ALLOW_UNAUTHENTICATED_CORE has no secret to check
    // against; a signature it cannot verify is worse than no signature.
    assert.deepEqual(signedHeaders(undefined, "GET", "/v1/runs/x"), {});
  });

  it("changes the signature when any signed component changes", () => {
    const base = signRequest(VECTOR.secret, VECTOR.timestamp, VECTOR.canonical);
    assert.notEqual(base, signRequest(VECTOR.secret, VECTOR.timestamp + 1, VECTOR.canonical));
    assert.notEqual(base, signRequest(VECTOR.secret, VECTOR.timestamp, canonicalPayload("GET", VECTOR.path, VECTOR.body)));
    assert.notEqual(base, signRequest(VECTOR.secret, VECTOR.timestamp, canonicalPayload(VECTOR.method, "/v1/turns", VECTOR.body)));
    assert.notEqual(base, signRequest(VECTOR.secret, VECTOR.timestamp, canonicalPayload(VECTOR.method, VECTOR.path, "{}")));
  });
});

function stubFetch(handler: (url: string, init: RequestInit) => { status?: number; body?: unknown }) {
  const calls: Array<{ url: string; init: RequestInit }> = [];
  const impl = (async (url: unknown, init: unknown) => {
    const i = (init ?? {}) as RequestInit;
    calls.push({ url: String(url), init: i });
    const r = handler(String(url), i);
    const status = r.status ?? 200;
    return {
      ok: status >= 200 && status < 300,
      status,
      text: async () => (r.body === undefined ? "" : JSON.stringify(r.body)),
    };
  }) as unknown as typeof fetch;
  return { impl, calls };
}

describe("calling the core", () => {
  it("signs every request at call time, not at construction", async () => {
    // A queued request held past the five-minute replay window would be rejected
    // if it carried a timestamp from whenever the client was built.
    let clock = 1_700_000_000_000;
    const { impl, calls } = stubFetch(() => ({ body: { status: "ok" } }));
    const client = createCoreClient({
      baseUrl: "http://core",
      signingSecret: VECTOR.secret,
      fetchImpl: impl,
      now: () => clock,
    });
    await client.run("a");
    clock += 600_000;
    await client.run("b");
    const stamps = calls.map((c) => (c.init.headers as Record<string, string>)["x-timestamp"]);
    assert.deepEqual(stamps, ["1700000000", "1700000600"]);
  });

  it("signs the path with its query string, because upstream signs that", async () => {
    const { impl, calls } = stubFetch(() => ({ body: { status: "queued", runId: "r1" } }));
    const client = createCoreClient({ baseUrl: "http://core/", signingSecret: VECTOR.secret, fetchImpl: impl });
    await client.queueTurn({
      surface: "t",
      actor: { externalId: "U1" },
      conversation: { kind: "dm", threadRef: "th" },
      text: "hi",
    });
    assert.equal(calls[0]!.url, "http://core/v1/turns?async=1");
  });

  it("raises the core's status and body instead of a generic failure", async () => {
    const { impl } = stubFetch(() => ({ status: 401, body: { error: "bad signature" } }));
    const client = createCoreClient({ baseUrl: "http://core", fetchImpl: impl });
    await assert.rejects(
      () => client.run("r1"),
      (e: unknown) => e instanceof CoreError && e.status === 401 && /bad signature/.test(e.message),
    );
  });

  it("does not retry — one call is one attempt", async () => {
    // A retry hidden in the transport makes one attempt look like one call when
    // it was three, and the attempt record is supposed to be what happened.
    let n = 0;
    const { impl } = stubFetch(() => {
      n += 1;
      return { status: 500, body: { error: "boom" } };
    });
    const client = createCoreClient({ baseUrl: "http://core", fetchImpl: impl });
    await assert.rejects(() => client.run("r1"));
    assert.equal(n, 1);
  });
});

describe("waiting for a run", () => {
  const terminalCases = ["ok", "failed", "aborted", "rejected"];
  for (const status of terminalCases) {
    it(`treats '${status}' as terminal`, () => assert.ok(isTerminal(status)));
  }
  it("does not treat a running state as terminal", () => {
    assert.ok(!isTerminal("running"));
    assert.ok(!isTerminal("queued"));
    assert.ok(!isTerminal("pending"));
  });

  it("polls until the run reaches a terminal state", async () => {
    const states = ["queued", "running", "running", "ok"];
    let i = 0;
    const { impl } = stubFetch(() => ({ body: { status: states[Math.min(i++, states.length - 1)] } }));
    const client = createCoreClient({ baseUrl: "http://core", fetchImpl: impl });
    const out = await client.awaitRun("r1", { intervalMs: 0, sleep: async () => {} });
    assert.equal(out.status, "ok");
    assert.equal(i, 4);
  });

  it("reports a timeout as a state rather than throwing", async () => {
    // A step that timed out is a step whose attempt failed and can be retried;
    // a thrown error here would lose the run id the attempt needs to record.
    let clock = 0;
    const { impl } = stubFetch(() => ({ body: { status: "running", id: "r1" } }));
    const client = createCoreClient({ baseUrl: "http://core", fetchImpl: impl, now: () => clock });
    const out = await client.awaitRun("r1", {
      intervalMs: 0,
      timeoutMs: 10,
      sleep: async () => {
        clock += 100;
      },
    });
    assert.equal(out.status, "timeout");
    assert.equal(out.id, "r1");
  });
});
